version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000"
    depends_on:
      - db
    networks:
      - app-network 

  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1111:80"
    depends_on:
      - app
    networks:
      - app-network
  db:
    image: "mysql:latest"
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:MY-PASS
    networks:
      - app-network  
volumes:
    mysql: {}
networks:
    app-network: {}
~
~
