apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: webapp
      image: nginx
      volumeMounts:
      - mountPath: "/var/log/nginx"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: claim-log-1